name: Generate ASCII Artwork 

on:
    push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
          
        - name: List Reop Files 
          run: ls -ltra

        - name: Executing Shell Script
          run: |
            chomd +x ascii-script.sh
            ./ascii-script.sh
